#!/usr/bin/env python2
# -*- coding: UTF-8 -*-
#import gi
#gi.require_version('Gtk', '3.0')
#from gi.repository import Gtk #, Gtk.glade
import  threading
import string, os, sys, time, locale, gtk, gtk.glade, gnome


def find_lib():
    h, t = os.path.split(os.path.split(os.path.abspath(sys.argv[0]))[0])
    return os.path.join(h, t, "..")

print(find_lib())
sys.path.insert(0, find_lib())

from gnomecatalog.ui.app import *
from gnomecatalog.ui import dialogs


DIR = None
APP = "gnomecatalog"

import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
gettext.bindtextdomain(APP, DIR)
gettext.textdomain(APP)
gettext.install(APP, DIR, unicode=1)
gtk.glade.bindtextdomain (APP, "/usr/share/locale")
gtk.glade.textdomain (APP)


app_name = "Gnome Catalog"
app_version = '0.3.4.2'
app_authors = ["José Sánchez Moreno <jose@o2w.es>"]
app_translators = _("Translators credits")
#gnome_program = gnome.program_init(app_name, app_version)

class GnomeCatalog(App):

    def __init__(self):
        App.__init__(self,  {'name' : app_name, 'version' : app_version, 'authors' : app_authors, 'translators' : app_translators })

    def run(self):
        gtk.main()

if __name__ == "__main__":
    app = GnomeCatalog()
    app.run()
